# Generated by Django 5.0 on 2023-12-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0002_feature_experience1_feature_experience2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='experience1',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='experience2',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='experience3',
        ),
    ]
